@startuml clases

' =========================
' USUARIOS
' =========================

abstract class Usuario {
    - id: int 
    - nombre: String 
    - correo: String 
    + iniciarSesion(): boolean
}

class Cliente extends Usuario {
    direccion: String 
}

class Administrador extends Usuario {
    + gestionarProductos(): void
}

' =========================
' PRODUCTOS
' =========================

abstract class Producto {
    - id: int 
    - nombre: String 
    - precio: double 
    -stock: int 
    + calcularCostoEnvio(): double 
}

class Categoria {
    - nombre: String 
}

class Franquicia {
    - nombre: String 
}

Producto --> Categoria 
Producto --> Franquicia

' =========================
' PRODUCTOS EDITORIALES
' =========================

abstract class ProductoEditorial extends Producto {
    - autor: String
}

class Manga extends ProductoEditorial 
class Manhwa extends ProductoEditorial
class NovelaLigera extends ProductoEditorial

' =========================
' MERCHANDISING
' =========================

abstract class Merchandising extends Producto

class Ropa extends Merchandising
class Accesorio extends Merchandising
class Poster extends Merchandising

' =========================
' OTROS PRODUCTOS
' =========================

class FiguraColeccionable extends Producto 
class AlbumMuscial extends Producto

' =========================
' CARRITO
' =========================

class CarritoDeCompras {
    + agregarProducto(): void
    + eliminarProducto(): void
}

class IntemCarrito {
    - cantidad: int
}

Cliente --> CarritoDeCompras 
CarritoDeCompras --> IntemCarrito
IntemCarrito --> Producto

' =========================
' PEDIDOS
' =========================